services:
  - type: web
    name: leave-tracker-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && flask db upgrade && python init_db.py
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://leave_tracker_db_u4kr_user:NM9cLVXmvLUspsMV37OVf4woCQiWTOxl@dpg-d6bd438gjchc73ahtlkg-a/leave_tracker_db_u4kr
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_APP
        value: app.py
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/static/uploads
      - key: MAX_CONTENT_LENGTH
        value: 16000000
